remove fixed footer also
unitedstates/contact-congress pull request #2386
Opened 2023-07-04 04:17 UTC by DrMeers

2023-07-04 13:47 UTC, j-ro requested changes

2023-07-04 13:47 UTC, j-ro commented on members/W000790.yaml
> +        - value: "document.querySelector('.elementor-location-footer')?.remove();"
does this work on your implementation? It doesn't on ours, you need separate javascript statements.

2023-07-05 06:54 UTC, DrMeers commented on members/W000790.yaml
> +        - value: "document.querySelector('.elementor-location-footer')?.remove();"
yes this works fine on our implementation, but I can separate the statements for yours

2023-07-05 07:00 UTC, DrMeers commented on members/W000790.yaml
> +        - value: "document.querySelector('.elementor-location-footer')?.remove();"
yours would also have issues with https://github.com/unitedstates/contact-congress/commits/master/members/S000148.yaml etc then?

2023-07-05 07:01 UTC, DrMeers commented on members/W000790.yaml
> +        - value: "document.querySelector('.elementor-location-footer')?.remove();"
see commit below please @j-ro

2023-07-05 13:28 UTC, merged